version: "3.8"

services:
  db:
    image: postgres:16.4
    container_name: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: homeworkmanager
    volumes:
      - ./internal/db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/mydatabase?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8888:8888"

volumes:
  db_data:
  redis_data:



